name: smartband
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  google_sign_in: ^6.2.1
  # flutter_blue: ^0.8.0
  permission_handler: ^11.3.1
  cloud_firestore: ^5.0.2
  smooth_page_indicator: ^1.1.0
  flutter_riverpod: ^2.5.1
  rxdart: ^0.26.0
  geolocator: ^7.0.1
  flutter_blue_plus: ^1.12.0
  flutter_background_service: ^5.0.7
  flutter_background_service_android: ^6.2.4
  font_awesome_flutter: ^10.7.0
  geocoding: ^3.0.0
  url_launcher: ^6.3.0
  flutter_callkit_incoming: ^2.0.4+1
  flutter_overlay_window: ^0.4.5
  flutter_countdown_timer: ^4.1.0
  volume_controller: ^2.0.8
  firebase_messaging: ^15.0.3
  firebase_analytics: ^11.2.0
  googleapis_auth: ^1.6.0
  flutter_local_notifications: ^17.2.2
  flutter_background: ^1.2.0
  just_audio: ^0.9.39
  audio_session: ^0.1.21
  audioplayers: ^6.0.0
  intl_phone_field: ^3.2.0
  chewie: ^1.8.2
  video_player: ^2.9.1
  crypto: ^3.0.3
  intl: ^0.19.0
  http: ^1.2.2
  provider: ^6.1.2
  android_intent_plus: ^5.2.0
  google_maps_flutter: ^2.9.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  shared_preferences: ^2.3.2
  workmanager: ^0.5.2 
  cron: ^0.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
